version: 2
jobs:
  build:
    docker:
      - image: jumperio/vlab-gcc-arm:latest
    steps:
      - checkout
      - run:
          name: build
          command: make
      - run:
          name: test
          pwd: BUILD/
          command: python test.py
      - store_artifacts:
          path: BUILD/